### ISSUE TITLE
[request] export the grid when building the app

### ISSUE THREAD

**Issue by bouzidmiloud** [BeardScript/RogueEngine#1]
hi is it possible to add this feature  to export the grid from the scene editor  into the final build .
it would be great to have the system to get it on specific scene also not all at the same time.

**Comment by Njabe91** [comment]
> hi is it possible to add this feature  to export the grid from the scene editor  into the final build .
> it would be great to have the system to get it on specific scene also not all at the same time.
> 
>

**Comment by BeardScript** [comment]
This should be done by adding a three.js GridHelper from a component at runtime.

https://threejs.org/docs/#api/en/helpers/GridHelper
